"""initial schema

Revision ID: 029c7f466756
Revises: 
Create Date: 2026-09-20 10:40:57.396503
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '029c7f466756'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrateur',
    sa.Column('id_administrateur', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_administrateur')
    )
    op.create_table('creneau_horaire',
    sa.Column('id_creneau', sa.Integer(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id_creneau')
    )
    op.create_table('guide',
    sa.Column('id_guide', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_guide')
    )
    op.create_table('parcours',
    sa.Column('id_parcours', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id_parcours')
    )
    op.create_table('visiteur',
    sa.Column('id_visiteur', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_visiteur')
    )
    op.create_table('message',
    sa.Column('id_message', sa.Integer(), nullable=False),
    sa.Column('contenu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.Enum('NON_LU', 'LU', 'REPONDU', name='statutmessage'), nullable=False),
    sa.Column('id_visiteur', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_visiteur'], ['visiteur.id_visiteur'], ),
    sa.PrimaryKeyConstraint('id_message')
    )
    op.create_table('visite',
    sa.Column('id_visite', sa.Integer(), nullable=False),
    sa.Column('date_visite', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'EFFECTUEE', 'NON_EFFECTUEE', name='statutvisite'), nullable=False),
    sa.Column('nombre_personnes', sa.Integer(), nullable=False),
    sa.Column('id_visiteur', sa.Integer(), nullable=False),
    sa.Column('id_parcours', sa.Integer(), nullable=False),
    sa.Column('id_creneau', sa.Integer(), nullable=False),
    sa.Column('id_guide', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_creneau'], ['creneau_horaire.id_creneau'], ),
    sa.ForeignKeyConstraint(['id_guide'], ['guide.id_guide'], ),
    sa.ForeignKeyConstraint(['id_parcours'], ['parcours.id_parcours'], ),
    sa.ForeignKeyConstraint(['id_visiteur'], ['visiteur.id_visiteur'], ),
    sa.PrimaryKeyConstraint('id_visite')
    )
    op.create_table('reponse',
    sa.Column('id_reponse', sa.Integer(), nullable=False),
    sa.Column('contenu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=False),
    sa.Column('id_message', sa.Integer(), nullable=False),
    sa.Column('id_administrateur', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_administrateur'], ['administrateur.id_administrateur'], ),
    sa.ForeignKeyConstraint(['id_message'], ['message.id_message'], ),
    sa.PrimaryKeyConstraint('id_reponse'),
    sa.UniqueConstraint('id_message')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reponse')
    op.drop_table('visite')
    op.drop_table('message')
    op.drop_table('visiteur')
    op.drop_table('parcours')
    op.drop_table('guide')
    op.drop_table('creneau_horaire')
    op.drop_table('administrateur')
    # ### end Alembic commands ###