"""initial schema

Revision ID: eca788fc38f8
Revises: 029c7f466756
Create Date: 2026-09-21 18:59:39.589875
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'eca788fc38f8'
down_revision: Union[str, Sequence[str], None] = '029c7f466756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrateur', 'prenom',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'administrateur', ['email'])
    op.alter_column('guide', 'prenom',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'guide', ['telephone'])
    op.alter_column('visiteur', 'prenom',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'visiteur', ['email'])
    op.create_unique_constraint(None, 'visiteur', ['telephone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'visiteur', type_='unique')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'visiteur', type_='unique')
    op.alter_column('visiteur', 'prenom',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'guide', type_='unique')
    op.alter_column('guide', 'prenom',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'administrateur', type_='unique')
    op.alter_column('administrateur', 'prenom',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###